SQL Commands  SELECT : get the data
     *  : All data
   Select * from STUDENT_TEST

select name from STUDENT_TEST

select section from STUDENT_TEST


########## restrict the rows

select * from STUDENT_TEST where name ='Raj'

select * from STUDENT_TEST where section='CS'

select * from STUDENT_TEST where age=23



SYNTAX :INSERT

INSERT INTO TABLE_NAME VALUES (VALUE1,VALUE2.....)

INSERT INTO STUDENT_TEST VALUES('MUKESH',25,'IT')

INSERT INTO STUDENT_TEST VALUES('RAJESH',20,'CS')

SYNTAX: UPDATE
UPDATE TABLE_NAME SET COLUMN= VALUE WHERE COLUMN=VALUE

UPDATE STUDENT_TEST SET SECTION='IT' WHERE NAME='RAHUL'

UPDATE STUDENT_TEST SET AGE=20 WHERE NAME='MUKESH'

UPDATE STUDENT_TEST SET AGE=20

SELECT * FROM STUDENT_TEST

SYNTAX: DELETE

DELETE FROM TABLE_NAME WHERE COLUMN=VALUE

DELETE FROM STUDENT_TEST WHERE NAME ='MUKESH'

DELETE FROM STUDENT_TEST WHERE SECTION='IT'